package edu.uic.ibeis_java_api.test;

import edu.uic.ibeis_java_api.utils.FileUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.*;

;

public class FileUtilsTestCollection implements TestCollection {

    private Collection<Test> testCollection;

    // files generated by the tests
    private Collection<File> testGeneratedFiles;

    public FileUtilsTestCollection() {
        System.out.println("***FILE UTILS TEST COLLECTION***\n");
        testCollection = new ArrayList<>();
        testGeneratedFiles = new ArrayList<>();

        testCollection.add(new ZipFileTest(new File(getClass().getClassLoader().getResource("zebra_api_upload_test.jpeg").getFile())));
        testCollection.add(new ZipFileTest(Arrays.asList(new File(getClass().getClassLoader().getResource("zebra_api_upload_test.jpeg").getFile()),
                new File(getClass().getClassLoader().getResource("giraffe_api_upload_test.jpeg").getFile()))));
    }

    public void runTests() {
        for(Test t : testCollection) {
            t.execute();
            System.out.print("\n");
        }
        // delete all files generated by tests
        deleteGeneratedFiles();
        System.out.print("\n\n");
    }

    /**
     * Delete all the files generated by the tests in the collection
     */
    public void deleteGeneratedFiles() {
        try {
            for (File f : testGeneratedFiles) {
                Files.delete(f.toPath());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    private class ZipFileTest implements Test {

        private List<File> filesToZip;

        public ZipFileTest(File file) {
            filesToZip = new ArrayList<>();
            filesToZip.add(file);
        }

        public ZipFileTest(List<File> files) {
            filesToZip = new ArrayList<>(files);
        }

        @Override
        public String getTestType() {
            return this.getClass().getSimpleName();
        }

        @Override
        public void execute() {
            File testArchivePath = new File(System.getProperty("user.home") + "/ibeis_test_" + new SimpleDateFormat("MM-dd-yyyy_HH:mm:ss_SSS").format(new Date()) + ".zip");
            testGeneratedFiles.add(testArchivePath);

            try {
                if (filesToZip.size() == 1) {
                    File file = filesToZip.get(0);
                    FileUtils.zipFile(file, testArchivePath);
                    System.out.println(getTestType() + ": file \"" + file.getPath() + "\" successfully zipped into archive \"" + testArchivePath + "\"");
                }
                else {
                    FileUtils.zipFiles(filesToZip, testArchivePath);
                    System.out.println(getTestType() + ": files " + formatFilesList(filesToZip) + " successfully zipped into archive \"" + testArchivePath + "\"");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        private String formatFilesList(List<File> files) {
            StringBuilder builder = new StringBuilder("");

            for(int i=0; i<files.size(); i++) {
                if(i < files.size()-1) {
                    builder.append("\"" + files.get(i).getPath() + "\", ");
                }
                else {
                    builder.append("\"" + files.get(i).getPath() + "\"");
                }
            }
            return builder.toString();
        }
    }
}
